repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: ^(data|patches)/.*$
      - id: end-of-file-fixer
        exclude: ^(data|patches)/.*$
      - id: check-yaml
        exclude: ^data/

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.5
    hooks:
      - id: clang-format
        name: Fix *.c,*.cc,*.cpp,*.h,*.hpp
        files: ^(src|python|tools|tests|examples)/.*\.(c|cc|cpp|h|hpp)$
        args: ["-style=Google"]
