services:
  dev:
    image: chengcli/kintera:dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        CUDA_VER: "12.9.1"
        UBUNTU_VER: "22.04"
        USERNAME: "${USER}"
        USER_UID: "${UID:-1000}"
        USER_GID: "${GID:-1000}"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]   # requires Compose v2 + nvidia toolkit
    volumes:
      - ./:/workspace
      - ${HOME}/data/:/data
      - ccache:/ccache
    working_dir: /workspace
    tty: true
    stdin_open: true
    ports:
      - "8888:8888"
volumes:
  ccache:

